version: '3.1'

services:
  ui:
    build: ./air-statistic-app-ui/.
    container_name: air-statistic-app-ui
    restart: always
    ports:
      - 8080:80
  db:
    image: postgres:14.0
    container_name: air-statistic-app-data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: AirFreeDB
      POSTGRES_USER: air-free
      POSTGRES_PASSWORD: air-free
      PGDATA: /var/lib/postgresql/data/database
      POSTGRES_INITDB_ARGS: '--encoding=WIN1250 --lc-collate=C --lc-ctype=C'
    volumes:
       - ./air-statistic-app-data/create_tables.sql:/docker-entrypoint-initdb.d/setup.sql
       - ./air-statistic-app-data/raw_data:/raw_data
  pgadmin:
    image: dpage/pgadmin4:6.2
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
