version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: AirFreeDB
      POSTGRES_USER: air-free
      POSTGRES_PASSWORD: air-free
      PGDATA: /var/lib/postgresql/data/database
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --lc-collate=C --lc-ctype=C'
    volumes:
       - ./create_tables.sql:/docker-entrypoint-initdb.d/setup.sql
       - ../raw_data:/raw_data

  adminer:
    image: adminer
    restart: always
    ports:
      - 9081:8080


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root

    ports:
      - "5050:80"
